#@baseUrl = https://localhost:7092
@baseUrl = http://localhost:8888

GET {{baseUrl}}/health

### Realizar a coleta dos ativos

GET {{baseUrl}}/collect-stock?stock=PETR4.SA


###

GET {{baseUrl}}/list-stocks?stock=PETR4.SA


### API Yahoo

@inicio = 1703701377
@fim = 1706293377
GET https://query2.finance.yahoo.com/v8/finance/chart/PETR4.SA?period1={{inicio}}&period2={{fim}}&interval=1d
